monolog:
    channels:
        - deprecation

    handlers:
        errors_filter:
            type: fingers_crossed
            action_level: error
            handler: errors
            excluded_http_codes: [404, 405]

        errors:
            type: rotating_file
            max_files: 14
            path: "%kernel.logs_dir%/errors.log"
            level: error

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            development_debug:
                type: rotating_file
                max_files: 1
                path: "%kernel.logs_dir%/debug.log"
                level: debug
                channels:
                    - "!event"
