parameters:

services:
    _defaults: &defaults
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


when@test:
    services:
        _defaults: *defaults

        App\Tests\Behat\:
            resource: '../tests/Behat/*'
